wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.5
    cli_version: 0.16.6
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: true
    start_time: 1712254044.0
    t:
      1:
      - 1
      - 5
      - 12
      - 41
      - 53
      - 55
      2:
      - 1
      - 5
      - 12
      - 41
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.11.5
      5: 0.16.6
      8:
      - 1
      - 2
      - 4
      - 5
      13: darwin-arm64
